# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-30 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='text_en',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='new',
            name='text_ja',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
