# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-02 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20171030_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('colloquium', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=500, null=True)),
                ('volume', models.CharField(max_length=100, null=True)),
                ('number', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='papers',
            field=models.ManyToManyField(to='homepage.Paper'),
        ),
    ]
