# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-30 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text_ja', models.TextField(blank=True, max_length=200)),
                ('text_en', models.TextField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='./images')),
            ],
        ),
    ]
